kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: slotegrator-test-memorytest
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: slotegrator-test
  mode: one
  stressors:
    memory:
      workers: 4
      size: 512MB
